name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@4
      with:
        node-version: 20
      
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run test
      run: npm test

    - name: Build
      run: npm run build:dev
